# Problem: Real-Time System Log Analyzer (While Loop)

# Context (Market-Oriented)

# You are building a monitoring module for a cloud service.
# The system receives a continuous list of log events generated by servers
# Each event is represented as a tuple: (event_type, response_time_ms)

# "OK" → normal request
# "SLOW" → request took too long
# "ERROR" → system failure
# "SHUTDOWN" → stop processing logs (sentinel value)

# logs = [
#     ("OK", 120),
#     ("OK", 95),
#     ("SLOW", 850),
#     ("OK", 110),
#     ("ERROR", 0),
#     ("SLOW", 920),
#     ("OK", 130),
#     ("SHUTDOWN", -1),
#     ("OK", 100)  # must NOT be processed
# ]

# Your Tasks

# Using ONLY a while loop to iterate through the list:
# Stop processing when the event "SHUTDOWN" is found.
# Count:
# total number of processed events
# number of "ERROR" events
# number of "SLOW" events
# Calculate:
# average response time of "OK" events only
# If 3 or more "ERROR" events occur, stop immediately (early exit).
# Print a final system summary report.

# Data list

logs = [
    
     ("OK", 120),
     ("OK", 95),
     ("SLOW", 850),
     ("OK", 110),
     ("ERROR", 0),
     ("SLOW", 920),
     ("OK", 130),
     ("ERROR", -1),
     ("ERROR", 100),
     ("ERROR", 22),
     ("OK", 90)
 ]

# Iniciating counters

i = 0
count_ok = 0
count_error=0
count_slow=0
time_response = 0
events_processed = 0
system_critical = False

# iterating over list using "while" condition

while i < len(logs):

  # item represents each tuple of list.
  item = logs[i]
  # Here I´m going to access index of tuple and stablish conditions...

  if item[0] == "OK":

    count_ok+=1
    print("Normal request")
    time_response = time_response + item[1]
    events_processed+=1
    

  elif item[0] == "SLOW":
    count_slow+=1
    print("Request took too long")
    events_processed+=1
    

  elif item[0] == "ERROR":

    print("System failure")
    stable = 0
    count_error+=1
    events_processed+=1

    if count_error >= 3:
      system_critical = True
      break

  elif item[0] == "SHUTDOWN":
    events_processed+=1
    print("Stop processing...")
    break

  i+=1

def System_summary_report(average_response, count_slow, count_error, system_critical, events_processed):

  if system_critical:
    status = "UNSTABLE"
  else:
    status = "STABLE"

  if count_ok != 0:
    average_response = time_response/count_ok
  else:
    average_response = 0

  print(" ")
  print("System Monitoring Report")
  print(4*"-----------") 
  print(f'Events processed {events_processed}')
  print(f'OK events average reponse time: {average_response}')
  print(f'Slow requests: {count_slow}')
  print(f'Erros detected: {count_error}')
  print(f'System status: {status}')
  


System_summary_report(time_response, count_slow, count_error, system_critical, events_processed)



